### ISSUE TITLE
CAR_2013_04_002 error

### ISSUE THREAD

**Issue by infosec-alchemist** [unfetter-analytic/unfetter#1]
This analytic caused an error:
File "/usr/share/unfetter/src/CAR_2013_04_002.py", line 129, in group_suspicous_processes
item[1]['utc_datetime'] = datetime.strptime(item[1]['utc_time'], "%Y-%m-%d %H:%M:%S.%f")
time data '2016-12-08T07:42:04Z' does not match format '%Y-%m-%d %H:%M:%S.%f'

**Comment by vini-m** [comment]
@infosec-alchemist could the filter be like this? `'%Y-%m-%dT%H:%M:%SZ'`
It's kinda hacky, but works. 
It appears this time data accords to RFC 3339. There's an open [issue ](https://bugs.python.org/issue15873) on Python about that. 

You can also use `[dateutil.parser](https://stackoverflow.com/questions/127803/how-to-parse-an-iso-8601-formatted-date)`

**Comment by infosec-alchemist** [comment]
Oh thanks.  I'll give that a shot

**Comment by vini-m** [comment]
;)
