### ISSUE TITLE
Missing cti-stix-store

### ISSUE THREAD

**Issue by gromit6891** [unfetter-analytic/unfetter#21]
The call to create an index causes error relating to missing cti-stix-store. In the docker-compose file, the analytic-system container is listed twice - maybe one of them should be a cti-stix-store container.

`elasticsearch      | [2017-12-01T02:04:49,954][INFO ][o.e.c.m.MetaDataMappingService] [x3ZoUFc] [sitaware/WB_Rto20SnGgVu41iTd0bg] create                                                                                                                                _mapping [CAR_2013_10_001]
Traceback (most recent call last):
analytic-system    |   File "/usr/share/unfetter/src/run_unfetter_analytic.py", line 216, in <module>
analytic-system    |     postSTIXStore(analytic.car_data)
analytic-system    |   File "/usr/share/unfetter/src/run_unfetter_analytic.py", line 154, in postSTIXStore
analytic-system    |     response = requests.post(url, headers=headers, data=json.dumps(sighting))
analytic-system    |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 112, in post
analytic-system    |     return request('post', url, data=data, json=json, **kwargs)
analytic-system    |   File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 58, in request
analytic-system    |     return session.request(method=method, url=url, **kwargs)
analytic-system    |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
analytic-system    |     resp = self.send(prep, **send_kwargs)
analytic-system    |   File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
analytic-system    |     r = adapter.send(request, **kwargs)
analytic-system    |   File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 508, in send
analytic-system    |     raise ConnectionError(e, request=request)
analytic-system    | requests.exceptions.ConnectionError: HTTPConnectionPool(host='cti-stix-store', port=3000): Max retries exceeded wit                                                                                                                                h url: /cti-stix-store-api/sightings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc48f9ae290>: Failed                                                                                                                                 to establish a new connection: [Errno -2] Name or service not known',))`

**Comment by infosec-alchemist** [comment]
Thanks. 

The CTI-STIX-STORE is no longer used.  We moved to a different stack for our Unfetter Discover, and I haven't had a chance to fix them.

I will look at the double analytic system

**Comment by infosec-alchemist** [comment]
Depends on #13
