### ISSUE TITLE
Port changes in docker-compose.yml

### ISSUE THREAD

**Issue by hf-mitre** [unfetter-analytic/unfetter#58]
Hi,

I've been trying to get unfetter-analytic working with https://github.com/mitre/cascade-server . CASCADE uses the same data model, so it should go pretty smooth, but I've been running into trouble getting the pipeline deployed correctly. 

The forwarded ports in docker-compose.yml on `master` changed a while back, but it looks like logstash and the vagrant windows example are still forwarding to the  old ports (maybe this is related to the upcoming switch to beats?). I think the target network topology has the windows guest sending logs to the docker host which then forwards that traffic to the logstash container.  Though maybe there's also a way to bridge a virtualbox guest onto a docker network, which doesn't require having those ports forwarded by docker? 

I tried editing the docker-compose to also forward the old ports, but logstash kept crashing.  I want to make sure that I have the topology down right before I continue troubleshooting the logstash issue. 

Thanks!

**Comment by infosec-alchemist** [comment]
I now only have one port for Winlogbeat, 5044.  I'm rebuilding the data ingest so starting small. you should now be able to send winlogbeat to 5044 on the host machine. 

If you are sending different logs, then you will need to create the config files for them.

Try it out.  If there are problems, please let me know.

**Comment by unkempthenry** [comment]
Thanks!  I think my issue is basically that I was trying to use https://github.com/unfetter-analytic/windows-example which still uses nxlog.
